### ISSUE TITLE
How does both work together ?

### ISSUE THREAD

**Issue by human-divanshu** [zewa666/aurelia-node#10]
Can you explain in brief how you combined both aurelia and node. May be with help of simple block diagram. This would help a lot of people. 

Thanks a lot

**Comment by weoreference** [comment]
Hi Vildan!

I would be interested in this question also -- since I will like to understand it to help me with my own question: https://github.com/zewa666/aurelia-node/issues/9

Would appreciate instruction with this question also.

**Comment by zewa666** [comment]
Actually there is not too much about it. Aurelia is a Frontend framework thus all you need to do is to host it as static content. In case of this repo we get a Node ExpressJS application with a `public/app` folder hosting the skeleton navigation example.
The install procedure `bin/install` will get the latest available tag from the aurelia repository and put it in above mentioned static folder.
After you did npm/jspm installs running `gulp watch` from the root folder will fire up BrowserSync and run the backend as well as the frontend, where the backend runs by default on [port 9000](https://github.com/zewa666/aurelia-node/blob/master/app.js#L33) and BrowserSync proxies that one on [port 7000](https://github.com/zewa666/aurelia-node/blob/master/gulpfile.js#L107-L111).

There is really nothing else to it. You could as an example place whatever content you want under `public/app` or create another folder like `public/app2` and either adjust the [default route](https://github.com/zewa666/aurelia-node/blob/master/routes/api.js#L9-L11) or add a new one.

Hope this helps
