### ISSUE TITLE
Node version out of date?

### ISSUE THREAD

**Issue by julielerman** [zewa666/aurelia-node#11]
I get this when I npm install at root:
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} 
(current: {"node":"4.1.2","npm":"2.14.4"})

I'm not sure what change to make in package.json to fix this so wanted to let you know.

**Comment by zewa666** [comment]
I don't think this is an issue if aurelia-node but the karma runner itself declaring a wrong node dependency. Really not sure about this one, but frankly it doesn't really matter since this warning won't break the progress

**Comment by julielerman** [comment]
Got it that it doesn't hurt anything. And I haven't even tried running the tests anyway. And karma does work with nod And there are a million warns that I'm ignoring also. This one bugged me though for some reason. :) Just in case it's of interest : 

Karma's current version (v0.13.10) has this in package.json:
 "engines": {
    "node": "0.10 || 0.12 || 4"
  },

Maybe I'll just tweak your package.json to change
"karma": "^0.12.28" so it will also go for 0.13.

thanks!

**Comment by zewa666** [comment]
sounds like a plan :+1:
