### ISSUE TITLE
Example with Aurelia-CLI

### ISSUE THREAD

**Issue by ajile-in** [zewa666/aurelia-node#15]
Is it possible to provide another example with Aurelia CLI instead of using a Skeleton project?

**Comment by zewa666** [comment]
Its actually pretty simple. Aurelia-CLI scaffolds an app which runs on top of browsersync and gulp tasks.
So you can leverage that by:

* Creating a app.js to act as your node app
* Proxying the requests from browsersync to a node app
* Using nodemon for livereload
* Fixing up existing Aurelia-CLI run task.

So all need is actually two npm installs, a file app.js and just small adjustments to `aurelia_project/tasks.run.js`. Take a look at the gist below.

https://gist.github.com/zewa666/ca1d5b0cf1fdccd5f756948fa64c66dd

I hope this helps
